AWSTemplateFormatVersion: "2010-09-09"
Description: RAPIDアプリケーションをデプロイするためのCodeBuildプロジェクト（S3ソース使用）

Parameters:
  AllowedIpV4AddressRanges:
    Type: String
    Default: '["0.0.0.0/1","128.0.0.0/1"]'
    Description: フロントエンドWAFで許可するIPv4アドレス範囲（JSON配列形式）
  
  AllowedIpV6AddressRanges:
    Type: String
    Default: '["0000:0000:0000:0000:0000:0000:0000:0000/1","8000:0000:0000:0000:0000:0000:0000:0000/1"]'
    Description: フロントエンドWAFで許可するIPv6アドレス範囲（JSON配列形式）
  
  DisableIpv6:
    Type: String
    Default: "false"
    Description: IPv6サポートを無効にするかどうか
    AllowedValues: ["true", "false"]
  
  AutoMigrate:
    Type: String
    Default: "true"
    Description: デプロイ時に自動的にデータベースマイグレーションを実行するかどうか
    AllowedValues: ["true", "false"]
  
  CdkJsonOverride:
    Type: String
    Default: "{}"
    Description: CDK設定をオーバーライドするためのJSON文字列

  S3Bucket:
    Type: String
    Description: ソースコードが格納されているS3バケット名
  
  S3Key:
    Type: String
    Default: "rapid-code.zip"
    Description: ソースコードのZIPファイルのS3キー

Resources:
  ProjectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AdministratorAccess
  
  ProjectRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: Project
                    - :*
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: Project
          - Action:
              - codebuild:BatchPutCodeCoverages
              - codebuild:BatchPutTestCases
              - codebuild:CreateReport
              - codebuild:CreateReportGroup
              - codebuild:UpdateReport
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":codebuild:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :report-group/
                  - Ref: Project
                  - -*
          - Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":s3:::"
                  - Ref: S3Bucket
                  - /*
        Version: "2012-10-17"
      PolicyName: ProjectRoleDefaultPolicy
      Roles:
        - Ref: ProjectRole
  
  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: NO_CACHE
      EncryptionKey: alias/aws/s3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ALLOWED_IPV4_RANGES
            Value: !Ref AllowedIpV4AddressRanges
          - Name: ALLOWED_IPV6_RANGES
            Value: !Ref AllowedIpV6AddressRanges
          - Name: DISABLE_IPV6
            Value: !Ref DisableIpv6
          - Name: AUTO_MIGRATE
            Value: !Ref AutoMigrate
          - Name: CDK_JSON_OVERRIDE
            Value: !Ref CdkJsonOverride
          - Name: S3_BUCKET
            Value: !Ref S3Bucket
          - Name: S3_KEY
            Value: !Ref S3Key
      ServiceRole:
        Fn::GetAtt:
          - ProjectRole
          - Arn
      Source:
        BuildSpec: |-
          {
            "version": 0.2,
            "phases": {
              "install": {
                "runtime-versions": {
                  "nodejs": "20"
                },
                "on-failure": "ABORT",
                "commands": [
                  "npm install -g npm@latest"
                ]
              },
              "build": {
                "commands": [
                  "echo 'ビルドフェーズを開始します...'",
                  "echo 'S3からコードを取得中: s3://$S3_BUCKET/$S3_KEY'",
                  "mkdir -p /tmp/rapid-source",
                  "aws s3 cp s3://$S3_BUCKET/$S3_KEY /tmp/rapid-source/code.zip",
                  "unzip -q /tmp/rapid-source/code.zip -d /tmp/rapid-source",
                  "cd /tmp/rapid-source",
                  "ROOT_DIR=$(find . -mindepth 1 -maxdepth 1 -type d | head -n 1)",
                  "if [ -n \"$ROOT_DIR\" ]; then cd $ROOT_DIR; echo \"検出されたルートディレクトリ: $ROOT_DIR\"; else echo \"単一のルートディレクトリが見つかりませんでした。現在のディレクトリを使用します。\"; fi",
                  "echo 'パラメータを設定中...'",
                  "echo '/**' > cdk/lib/parameter.ts",
                  "echo ' * CDKデプロイのカスタムパラメータ設定ファイル' >> cdk/lib/parameter.ts",
                  "echo ' *' >> cdk/lib/parameter.ts",
                  "echo ' * このファイルは、CDKデプロイ時に使用するパラメータをカスタマイズするためのものです。' >> cdk/lib/parameter.ts",
                  "echo ' * デプロイスクリプトによって自動生成されました。' >> cdk/lib/parameter.ts",
                  "echo ' */' >> cdk/lib/parameter.ts",
                  "echo '' >> cdk/lib/parameter.ts",
                  "echo 'export const parameters = {' >> cdk/lib/parameter.ts",
                  "echo '  // WAF IP制限の設定' >> cdk/lib/parameter.ts",
                  "echo '  allowedIpV4AddressRanges: '$ALLOWED_IPV4_RANGES',' >> cdk/lib/parameter.ts",
                  "echo '  allowedIpV6AddressRanges: '$ALLOWED_IPV6_RANGES',' >> cdk/lib/parameter.ts",
                  "echo '' >> cdk/lib/parameter.ts",
                  "echo '  // Prismaマイグレーション設定' >> cdk/lib/parameter.ts",
                  "if [ \"$AUTO_MIGRATE\" = \"true\" ]; then echo '  autoMigrate: true,' >> cdk/lib/parameter.ts; else echo '  autoMigrate: false,' >> cdk/lib/parameter.ts; fi",
                  "echo '};' >> cdk/lib/parameter.ts",
                  "echo 'パラメータファイルを作成しました:'",
                  "cat cdk/lib/parameter.ts",
                  "echo 'CDK設定をカスタマイズ中...'",
                  "if [ ! -z \"$CDK_JSON_OVERRIDE\" ] && [ \"$CDK_JSON_OVERRIDE\" != \"{}\" ]; then echo \"$CDK_JSON_OVERRIDE\" | jq '.' && jq --argjson override \"$CDK_JSON_OVERRIDE\" '. * $override' cdk/cdk.json > temp.json && mv temp.json cdk/cdk.json; fi",
                  "echo 'バックエンドの準備...'",
                  "cd backend",
                  "npm ci",
                  "npm run prisma:generate",
                  "npm run build",
                  "cd ../cdk",
                  "echo 'CDKデプロイの準備...'",
                  "npm ci",
                  "npm run build",
                  "echo 'CDKデプロイを実行中...'",
                  "npx cdk bootstrap",
                  "npx cdk deploy --all --require-approval never"
                ]
              },
              "post_build": {
                "commands": [
                  "echo 'デプロイ完了！'",
                  "FRONTEND_URL=$(aws cloudformation describe-stacks --stack-name RapidStack --query \"Stacks[0].Outputs[?OutputKey=='FrontendURL'].OutputValue\" --output text)",
                  "API_URL=$(aws cloudformation describe-stacks --stack-name RapidStack --query \"Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue\" --output text)",
                  "echo \"フロントエンドURL: $FRONTEND_URL\"",
                  "echo \"API URL: $API_URL\"",
                  "echo \"FrontendURL = $FRONTEND_URL\""
                ]
              }
            }
          }
        Type: NO_SOURCE

Outputs:
  ProjectName:
    Value:
      Ref: Project
    Description: CodeBuildプロジェクト名
